export const CartActionTypes = {
  ADD_TO_CART_POST_LOADING: "ADD_TO_CART_POST_LOADING",
  ADD_TO_CART_POST_LOADED: "ADD_TO_CART_POST_LOADED",
  ADD_TO_CART_POST_ERROR: 'ADD_TO_CART_POST_ERROR',
  ADD_TO_CART_POST_RESET: 'ADD_TO_CART_POST_RESET',

  ADD_TO_CART_GET_LOADING: "ADD_TO_CART_GET_LOADING",
  ADD_TO_CART_GET_LOADED: "ADD_TO_CART_GET_LOADED",
  ADD_TO_CART_GET_ERROR: 'ADD_TO_CART_GET_ERROR',

  ADD_TO_CART_PATCH_LOADING: "ADD_TO_CART_PATCH_LOADING",
  ADD_TO_CART_PATCH_LOADED: "ADD_TO_CART_PATCH_LOADED",
  ADD_TO_CART_PATCH_ERROR: 'ADD_TO_CART_PATCH_ERROR',

  CART_PATCH_LOADING: "CART_PATCH_LOADING",
  CART_PATCH_LOADED: "CART_PATCH_LOADED",
  CART_PATCH_ERROR: 'CART_PATCH_ERROR',

  CUSTOMER_CART_LOADING: "CUSTOMER_CART_LOADING",
  CUSTOMER_CART_SUCCESS: "CUSTOMER_CART_LIST_SUCCESS",
  CUSTOMER_CART_FAIL: "CUSTOMER_CART_LIST_FAIL",
  CUSTOMER_CART_RESET: "CUSTOMER_CART_LIST_RESET",
  CART_QUANTITY_LOADING: "CART_QUANTITY_LOADING",

  GET_SHIPPING_DETAILS_LOADING: "GET_SHIPPING_DETAILS_LOADING",
  GET_SHIPPING_DETAILS_LOADED: "GET_SHIPPING_DETAILS_LOADED",
  GET_SHIPPING_DETAILS_RESET: "GET_SHIPPING_DETAILS_RESET",

    //shipping billing address flow
    
  GET_ADDRESS_LIST_LOADING: "GET_ADDRESS_LIST_LOADING",
  GET_ADDRESS_LIST_LOADED: "GET_ADDRESS_LIST_LOADED",
  GET_ADDRESS_LIST_ERROR: "GET_ADDRESS_LIST_ERROR",
  GET_ADDRESS_LIST_RESET: "GET_ADDRESS_LIST_RESET",

  POST_SHIPPING_BILLING_ADDRESS: "POST_SHIPPING_BILLING_ADDRESS",

  ADDRESS_OPERATIONS_SUCCESS: "ADDRESS_OPERATIONS_SUCCESS",

  ADDRESS_OPERATIONS_FAIL: "ADDRESS_OPERATIONS_FAIL",
  
  ADDRESS_OPERATIONS_LOADING: "ADDRESS_OPERATIONS_LOADING",

  PATCH_SHIPPING_BILLING_ADDRESS: "PATCH_SHIPPING_BILLING_ADDRESS",

  DELETE_SHIPPING_BILLING_ADDRESS: "DELETE_SHIPPING_BILLING_ADDRESS",

  UPDATE_SELECTED_ADDRESS_LOADING: "UPDATE_SELECTED_ADDRESS_LOADING",
  UPDATE_SELECTED_ADDRESS_LOADED: "UPDATE_SELECTED_ADDRESS_LOADED",
  UPDATE_SELECTED_ADDRESS_ERROR: "UPDATE_SELECTED_ADDRESS_ERROR",
  UPDATE_SELECTED_ADDRESS_RESET: "UPDATE_SELECTED_ADDRESS_RESET",

  CANCEL_CLIENT_ORDER_SUBORDER_LOADING:"CANCEL_CLIENT_ORDER_SUBORDER_LOADING",
  CANCEL_CLIENT_ORDER_SUBORDER_SUCCESS:"CANCEL_CLIENT_ORDER_SUBORDER_SUCCESS",

  UPDATE_ORDER_STATUS_BY_CUSTOMER_LOADING:"UPDATE_ORDER_STATUS_BY_CUSTOMER_LOADING",
  UPDATE_ORDER_STATUS_BY_CUSTOMER_SUCCESS:"UPDATE_ORDER_STATUS_BY_CUSTOMER_SUCCESS",
  UPDATE_ORDER_STATUS_BY_CUSTOMER_ERROR:"UPDATE_ORDER_STATUS_BY_CUSTOMER_ERROR",
  UPDATE_ORDER_STATUS_BY_CUSTOMER_RESET:"UPDATE_ORDER_STATUS_BY_CUSTOMER_RESET",


  GET_ALL_ORDERS_CLIENT_LOADING:"GET_ALL_ORDERS_CLIENT_LOADING",
  GET_ALL_ORDERS_CLIENT_SUCCESS:"GET_ALL_ORDERS_CLIENT_SUCCESS",
  GET_ALL_ORDERS_CLIENT_ERROR:"GET_ALL_ORDERS_CLIENT_ERROR",
  GET_ALL_ORDERS_CLIENT_RESET:"GET_ALL_ORDERS_CLIENT_RESET",
  CREATE_CART_ORDER_LOADING: "CREATE_CART_ORDER_LOADING",
  CREATE_CART_ORDER_SUCCESS: "CREATE_CART_ORDER_SUCCESS",
  CREATE_CART_ORDER_FAIL: "CREATE_CART_ORDER_FAIL",

  GET_SINGLE_ORDER_CLIENT_LOADING:"GET_SINGLE_ORDER_CLIENT_LOADING",
  GET_SINGLE_ORDER_CLIENT_SUCCESS:"GET_SINGLE_ORDER_CLIENT_SUCCESS",
  GET_SINGLE_ORDER_CLIENT_ERROR:"GET_SINGLE_ORDER_CLIENT_ERROR",
  GET_SINGLE_ORDER_CLIENT_RESET:"GET_SINGLE_ORDER_CLIENT_RESET",

  CANCEL_CLIENT_ORDER_LOADING:"CANCEL_CLIENT_ORDER_LOADING",
  CANCEL_CLIENT_ORDER_SUCCESS:'CANCEL_CLIENT_ORDER_SUCCESS',

  GET_SINGLE_ORDER_SUCCESS:"GET_SINGLE_ORDER_SUCCESS",
  UPDATE_ORDER_STATUS_REJECT:"UPDATE_ORDER_STATUS_REJECT",
  UPDATE_ORDER_STATUS_LOADING:"UPDATE_ORDER_STATUS_LOADING",

  CHANGE_ORDER_STATUS_LOADING: "CHANGE_ORDER_STATUS_LOADING",
  CHANGE_ORDER_STATUS_SUCCESS: "CHANGE_ORDER_STATUS_SUCCESS",
  CHANGE_ORDER_STATUS_FAIL: "CHANGE_ORDER_STATUS_FAIL",

  UPDATE_ORDER_STATUS_LOADING: "UPDATE_ORDER_STATUS_LOADING",
  UPDATE_ORDER_STATUS_SUCCESS: "UPDATE_ORDER_STATUS_SUCCESS",
  UPDATE_ORDER_STATUS_REJECT: "UPDATE_ORDER_STATUS_REJECT",
  UPDATE_ORDER_STATUS_RESET: "UPDATE_ORDER_STATUS_RESET",

  GET_FAIL_ITEM_LOADING: "GET_FAIL_ITEM_LOADING",
  GET_FAIL_ITEM_LOADED: "GET_FAIL_ITEM_LOADED",
  GET_DELIVER_ITEM_LOADING: "GET_DELIVER_ITEM_LOADING",
  GET_DELIVER_ITEM_LOADED: "GET_DELIVER_ITEM_LOADED",

  GET_SHIP_ITEM_LOADING: "GET_SHIP_ITEM_LOADING",
  GET_SHIP_ITEM_LOADED: "GET_SHIP_ITEM_LOADED",

  CUSTOMER_ORDER_DETAIL_LOADING: "CUSTOMER_ORDER_DETAIL_LOADING",
  CUSTOMER_ORDER_DETAIL_SUCCESS: "CUSTOMER_ORDER_DETAIL_SUCCESS",
  CUSTOMER_ORDER_DETAIL_FAIL: "CUSTOMER_ORDER_DETAIL_FAIL",
  CUSTOMER_ORDER_DETAIL_RESET: "CUSTOMER_ORDER_DETAIL_RESET",
}

