export const CategoryActionTypes = {
    ECOMM_ADMIN_CATEGORY_LIST_LOADING: "ECOMM_ADMIN_CATEGORY_LIST_LOADING",
    ECOMM_ADMIN_CATEGORY_LIST_LOADED: "ECOMM_ADMIN_CATEGORY_LIST_LOADED",
    ECOMM_ADMIN_CATEGORY_LIST_ERROR: "ECOMM_ADMIN_CATEGORY_LIST_ERROR",
    ECOMM_ADMIN_CATEGORY_LIST_RESET: "ECOMM_ADMIN_CATEGORY_LIST_RESET",


    SEARCH_CATEGORY_LIST_LOADED: "SEARCH_CATEGORY_LIST_LOADED",
}