export const Accept_Payment_Types = {
    POST_PARTIAL_CHARGES_LOADING: "POST_PARTIAL_CHARGES_LOADING",
    POST_PARTIAL_CHARGES_LOADED: "POST_PARTIAL_CHARGES_LOADED",
    POST_PARTIAL_CHARGES_ERROR: "POST_PARTIAL_CHARGES_ERROR",
    POST_PARTIAL_CHARGES_RESET: "POST_PARTIAL_CHARGES_RESET",

    GET_PARTIAL_CHARGES_LOADING: "GET_PARTIAL_CHARGES_LOADING",
    GET_PARTIAL_CHARGES_LOADED: "GET_PARTIAL_CHARGES_LOADED",
    GET_PARTIAL_CHARGES_ERROR: "GET_PARTIAL_CHARGES_ERROR",
    GET_PARTIAL_CHARGES_RESET: "GET_PARTIAL_CHARGES_RESET",

    UPDATE_PARTIAL_CHARGES_LOADING: "UPDATE_PARTIAL_CHARGES_LOADING",
    UPDATE_PARTIAL_CHARGES_LOADED: "UPDATE_PARTIAL_CHARGES_LOADED",
    UPDATE_PARTIAL_CHARGES_ERROR: "UPDATE_PARTIAL_CHARGES_ERROR",
    UPDATE_PARTIAL_CHARGES_RESET: "UPDATE_PARTIAL_CHARGES_RESET",
};