export const InstituteBlogsActionTypes = {
  GET_WEBSITE_BLOG_LIST_LOADING: "GET_WEBSITE_BLOG_LIST_LOADING",
  GET_WEBSITE_BLOG_LIST_LOADED: "GET_WEBSITE_BLOG_LIST_LOADED",
  GET_WEBSITE_BLOG_LIST_RESET: "GET_WEBSITE_BLOG_LIST_RESET",
  GET_WEBSITE_BLOG_LIST_ERROR: "GET_WEBSITE_BLOG_LIST_ERROR",


  GET_BLOG_LIST_LOADING: "GET_BLOG_LIST_LOADING",
  GET_BLOG_LIST_LOADED: "GET_BLOG_LIST_LOADED",
  GET_BLOG_LIST_RESET: "GET_BLOG_LIST_RESET",
  GET_BLOG_LIST_ERROR: "GET_BLOG_LIST_ERROR",

  GET_CATEGORY_LIST_LOADING: "GET_CATEGORY_LIST_LOADING",
  GET_CATEGORY_LIST_LOADED: "GET_CATEGORY_LIST_LOADED",
  GET_CATEGORY_LIST_RESET: "GET_CATEGORY_LIST_RESET",
  GET_CATEGORY_LIST_ERROR: "GET_CATEGORY_LIST_ERROR",
  LOCALAPI_CATEGORY_DATA: "LOCALAPI_CATEGORY_DATA",

  GET_SINGLE_CATEGORY_LOADING: "GET_SINGLE_CATEGORY_LOADING",
  GET_SINGLE_CATEGORY_LOADED: "GET_SINGLE_CATEGORY_LOADED",
  GET_SINGLE_CATEGORY_RESET: "GET_SINGLE_CATEGORY_RESET",
  GET_SINGLE_CATEGORY_ERROR: "GET_SINGLE_CATEGORY_ERROR",

  SEARCH_CATEGORY_BLOGS:"SEARCH_CATEGORY_BLOGS",
  LOCALAPISEARCH_CATEGORY_BLOGS:"LOCALAPISEARCH_CATEGORY_BLOGS",
}

