export const INS_BLOG_ACTION_TYPES = {
  GET_BLOG_LIST_LOADING: "GET_BLOG_LIST_LOADING",
  GET_BLOG_LIST_LOADED: "GET_BLOG_LIST_LOADED",
  GET_BLOG_LIST_RESET: "GET_BLOG_LIST_RESET",
  GET_BLOG_LIST_ERROR: "GET_BLOG_LIST_ERROR",
}