export const wishlistAction={
    GET_WISHLIST_LOADING: "GET_WISHLIST_LOADING",
    GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",
    GET_WISHLIST_FAIL: "GET_WISHLIST_FAIL",
    GET_WISHLIST_RESET: "GET_WISHLIST_RESET",
    MOVE_WISHLIST_TO_CART_LOADING: "MOVE_WISHLIST_TO_CART_LOADING",
    MOVE_WISHLIST_TO_CART_SUCCESS: "MOVE_WISHLIST_TO_CART_SUCCESS",
    MOVE_WISHLIST_TO_CART_FAIL: "MOVE_WISHLIST0_TO_CART_FAIL",
    // CUSTOMER_CART_FAIL:"CUSTOMER_CART_FAIL"
}