export const AppointmentActionTYpes = {
    GET_COLLECTION_LOADING: "GET_COLLECTION_LOADING",
    GET_COLLECTION_SUCCESS: "GET_COLLECTION_SUCCESS",
    GET_COLLECTION_ERROR: "GET_COLLECTION_ERROR",
    GET_COLLECTION_RESET: "GET_COLLECTION_RESET",

    GET_MAIN_CATEGORY_LIST_LOADING: "GET_MAIN_CATEGORY_LIST_LOADING",
    GET_MAIN_CATEGORY_LIST_SUCCESS: "GET_MAIN_CATEGORY_LIST_SUCCESS",
    GET_MAIN_CATEGORY_LIST_ERROR: "GET_MAIN_CATEGORY_LIST_ERROR",
    GET_MAIN_CATEGORY_LIST_RESET: "GET_MAIN_CATEGORY_LIST_RESET",

    GET_SERVICE_LIST_BY_CATEGOERY_LOADING: "GET_SERVICE_LIST_BY_CATEGOERY_LOADING",
    GET_SERVICE_LIST_BY_CATEGOERY_SUCCESS: "GET_SERVICE_LIST_BY_CATEGOERY_SUCCESS",
    GET_SERVICE_LIST_BY_CATEGOERY_ERROR: "GET_SERVICE_LIST_BY_CATEGOERY_ERROR",
    GET_SERVICE_LIST_BY_CATEGOERY_RESET: "GET_SERVICE_LIST_BY_CATEGOERY_RESET",
}