export const DISCOUNT_COUPON_TYPES = {
  GET_COUPON_LIST_LOADING:"GET_COUPON_LIST_LOADING",
  GET_COUPON_LIST_SUCCESS:"GET_COUPON_LIST_SUCCESS",
  GET_COUPON_LIST_ERROR:"GET_COUPON_LIST_ERROR",
  GET_COUPON_LIST_RESET:"GET_COUPON_LIST_RESET",

  CREATE_COUPON_LOADING:"CREATE_COUPON_LOADING",
  CREATE_COUPON_SUCCESS:"CREATE_COUPON_SUCCESS",
  CREATE_COUPON_ERROR:"CREATE_COUPON_ERROR",
  CREATE_COUPON_RESET:"CREATE_COUPON_RESET",

  EDIT_COUPON_LOADING:"EDIT_COUPON_LOADING",
  EDIT_COUPON_SUCCESS:"EDIT_COUPON_SUCCESS",
  EDIT_COUPON_ERROR:"EDIT_COUPON_ERROR",
  EDIT_COUPON_RESET:"EDIT_COUPON_RESET",

  GET_SINGLE_COUPON_LOADING:"GET_SINGLE_COUPON_LOADING",
  GET_SINGLE_COUPON_SUCCESS:"GET_SINGLE_COUPON_SUCCESS",
  GET_SINGLE_COUPON_ERROR:"GET_SINGLE_COUPON_ERROR",
  GET_SINGLE_COUPON_RESET:"GET_SINGLE_COUPON_RESET",

  DELETE_COUPON_LOADING:"DELETE_COUPON_LOADING",
  DELETE_COUPON_SUCCESS:"DELETE_COUPON_SUCCESS",
  DELETE_COUPON_ERROR:"DELETE_COUPON_ERROR",
  DELETE_COUPON_RESET:"DELETE_COUPON_RESET",

  DEACTIVATE_COUPON_LOADING:"DEACTIVATE_COUPON_LOADING",
  DEACTIVATE_COUPON_SUCCESS:"DEACTIVATE_COUPON_SUCCESS",
  DEACTIVATE_COUPON_ERROR:"DEACTIVATE_COUPON_ERROR",
  DEACTIVATE_COUPON_RESET:"DEACTIVATE_COUPON_RESET",

  GET_PRODUCT_LIST_LOADING:"GET_PRODUCT_LIST_LOADING",
  GET_PRODUCT_LIST_SUCCESS:"GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_ERROR:"GET_PRODUCT_LIST_ERROR",
  GET_PRODUCT_LIST_RESET:"GET_PRODUCT_LIST_RESET",

  GET_CATEGORY_LIST_LOADING:"GET_CATEGORY_LIST_LOADING",
  GET_CATEGORY_LIST_SUCCESS:"GET_CATEGORY_LIST_SUCCESS",
  GET_CATEGORY_LIST_ERROR:"GET_CATEGORY_LIST_ERROR",
  GET_CATEGORY_LIST_RESET:"GET_CATEGORY_LIST_RESET",

  DUPLICATE_COUPON_LOADING:"DUPLICATE_COUPON_LOADING",
  DUPLICATE_COUPON_SUCCESS:"DUPLICATE_COUPON_SUCCESS",
  DUPLICATE_COUPON_ERROR:"DUPLICATE_COUPON_ERROR",
  DUPLICATE_COUPON_RESET:"DUPLICATE_COUPON_RESET",

  CHECK_COUPON_AVAILABILITY_LOADING:"CHECK_COUPON_AVAILABILITY_LOADING",
  CHECK_COUPON_AVAILABILITY_SUCCESS:"CHECK_COUPON_AVAILABILITY_SUCCESS",

  GET_CUSTOMER_DISCOUNT_LIST_LOADING:"GET_CUSTOMER_DISCOUNT_LIST_LOADING",
  GET_CUSTOMER_DISCOUNT_LIST_SUCCESS:"GET_CUSTOMER_DISCOUNT_LIST_SUCCESS",
  GET_CUSTOMER_DISCOUNT_LIST_RESET:"GET_CUSTOMER_DISCOUNT_LIST_RESET",
  GET_CUSTOMER_DISCOUNT_LIST_ERROR:"GET_CUSTOMER_DISCOUNT_LIST_ERROR",

  APPLY_CUSTOMER_DISCOUNT_LOADING:"APPLY_CUSTOMER_DISCOUNT_LOADING",
  APPLY_CUSTOMER_DISCOUNT_SUCCESS:"APPLY_CUSTOMER_DISCOUNT_SUCCESS",
  APPLY_CUSTOMER_DISCOUNT_RESET:"APPLY_CUSTOMER_DISCOUNT_RESET",
  APPLY_CUSTOMER_DISCOUNT_ERROR:"APPLY_CUSTOMER_DISCOUNT_ERROR",

  REMOVE_APPLIED_COUPON_LOADING:"REMOVE_APPLIED_COUPON_LOADING",
  REMOVE_APPLIED_COUPON_LOADED:"REMOVE_APPLIED_COUPON_LOADED",
  REMOVE_APPLIED_COUPON_ERROR:"REMOVE_APPLIED_COUPON_ERROR",
  REMOVE_APPLIED_COUPON_RESET:"REMOVE_APPLIED_COUPON_RESET",
}