export const APPOINTMENTTYPES = {

  //appointment list
  POST_APPOINTMENT_LOADING: "POST_APPOINTMENT_LOADING",
  POST_APPOINTMENT_SUCCESS: "POST_APPOINTMENT_SUCCESS",
  POST_APPOINTMENT_ERROR: "POST_APPOINTMENT_ERROR",
  POST_APPOINTMENT_RESET: "POST_APPOINTMENT_RESET",

  //appointment list
  GET_ALL_SERVICES_LIST_LOADING: "GET_ALL_SERVICES_LIST_LOADING",
  GET_ALL_SERVICES_LIST_LOADED: "GET_ALL_SERVICES_LIST_LOADED",
  GET_ALL_SERVICES_LIST_ERROR: "GET_ALL_SERVICES_LIST_ERROR",
  GET_ALL_SERVICES_LIST_RESET: "GET_ALL_SERVICES_LIST_RESET",

  GET_SINGLE_SERVICE_LOADING: "GET_SINGLE_SERVICE_LOADING",
  GET_SINGLE_SERVICE_SUCCESS: "GET_SINGLE_SERVICE_SUCCESS",
  GET_SINGLE_SERVICE_ERROR: "GET_SINGLE_SERVICE_ERROR",
  GET_SINGLE_SERVICE_RESET: "GET_SINGLE_SERVICE_RESET",

  // ADMIN SIDE BOOKING LIST 
  GET_ALL_SLOTS_LOADING: "GET_ALL_SLOTS_LOADING",
  GET_ALL_SLOTS_LOADED: "GET_ALL_SLOTS_LOADED",
  GET_ALL_SLOTS_ERROR: "GET_ALL_SLOTS_ERROR",
  GET_ALL_SLOTS_RESET: "GET_ALL_SLOTS_RESET",

  POST_APPOINTMENT_CART_LOADING: "POST_APPOINTMENT_CART_LOADING",
  POST_APPOINTMENT_CART_SUCCESS: "POST_APPOINTMENT_CART_SUCCESS",
  POST_APPOINTMENT_CART_ERROR: "POST_APPOINTMENT_CART_ERROR",
  POST_APPOINTMENT_CART_RESET: "POST_APPOINTMENT_CART_RESET",

  GET_APPOINTMENT_CART_LOADING: "GET_APPOINTMENT_CART_LOADING",
  GET_APPOINTMENT_CART_SUCCESS: "GET_APPOINTMENT_CART_SUCCESS",
  GET_APPOINTMENT_CART_ERROR: "GET_APPOINTMENT_CART_ERROR",
  GET_APPOINTMENT_CART_RESET: "GET_APPOINTMENT_CART_RESET",


  GET_USER_SIDE_BOOKING_LIST_LOADING: "GET_USER_SIDE_BOOKING_LIST_LOADING",
  GET_USER_SIDE_BOOKING_LIST_LOADED: "GET_USER_SIDE_BOOKING_LIST_LOADED",
  GET_USER_SIDE_BOOKING_LIST_ERROR: "GET_USER_SIDE_BOOKING_LIST_ERROR",
  GET_USER_SIDE_BOOKING_LIST_RESET: "GET_USER_SIDE_BOOKING_LIST_RESET",
}