export const Review_ActionTypes = {

  SET_REVIEW_ID_SUCCESS: "SET_REVIEW_ID_SUCCESS",

  GET_PRODUCT_REVIEW_LOADING: "GET_PRODUCT_REVIEW_LOADING",
  GET_PRODUCT_REVIEW_LOADED: "GET_PRODUCT_REVIEW_LOADED",
  GET_PRODUCT_REVIEW_ERROR: "GET_PRODUCT_REVIEW_ERROR",
  GET_PRODUCT_REVIEW_RESET: "GET_PRODUCT_REVIEW_RESET",

  GET_BUYER_PRODUCT_RELATION:"GET_BUYER_PRODUCT_RELATION",
  
  POST_REVIEW_REPLY_LOADING: "POST_REVIEW_REPLY_LOADING",
  POST_REVIEW_REPLY_LOADED: "POST_REVIEW_REPLY_LOADED",
  POST_REVIEW_REPLY_ERROR: "POST_REVIEW_REPLY_ERROR",
  POST_REVIEW_REPLY_RESET: "POST_REVIEW_REPLY_RESET",
}