export const CREATEORDERTYPES = {
  GET_CUSTOMER_LIST_LOADING: "GET_CUSTOMER_LIST_LOADING",
  GET_CUSTOMER_LIST_SUCCESS: "GET_CUSTOMER_LIST_SUCCESS",
  GET_CUSTOMER_LIST_RESET: "GET_CUSTOMER_LIST_RESET",
  GET_CUSTOMER_LIST_ERROR: "GET_CUSTOMER_LIST_ERROR",

  POST_CUSTOMER_LOADING: "POST_CUSTOMER_LOADING",
  POST_CUSTOMER_SUCCESS: "POST_CUSTOMER_SUCCESS",
  POST_CUSTOMER_RESET: "POST_CUSTOMER_RESET",
  POST_CUSTOMER_ERROR: "POST_CUSTOMER_ERROR",

  PATCH_CUSTOMER_LOADING: "PATCH_CUSTOMER_LOADING",
  PATCH_CUSTOMER_SUCCESS: "PATCH_CUSTOMER_SUCCESS",
  PATCH_CUSTOMER_RESET: "PATCH_CUSTOMER_RESET",
  PATCH_CUSTOMER_ERROR: "PATCH_CUSTOMER_ERROR",

  POST_ORDER_LOADING: "POST_ORDER_LOADING",
  POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS",
  POST_ORDER_RESET: "POST_ORDER_RESET",
  POST_ORDER_ERROR: "POST_ORDER_ERROR",


  POST_DONATION_LOADING: "POST_DONATION_LOADING",
  POST_DONATION_SUCCESS: "POST_DONATION_SUCCESS",
  POST_DONATION_RESET: "POST_DONATION_RESET",
  POST_DONATION_ERROR: "POST_DONATION_ERROR",


  POST_CARD_SAVE_LOADING: "POST_CARD_SAVE_LOADING",
  POST_CARD_SAVE_LOADED: "POST_CARD_SAVE_LOADED",
  POST_CARD_SAVE_RESET: "POST_CARD_SAVE_RESET",
  POST_CARD_SAVE_ERROR: "POST_CARD_SAVE_ERROR",
  SUCCESS_POPUP_LOADED: "SUCCESS_POPUP_LOADED",
  ERROR_POPUP_LOADED: "ERROR_POPUP_LOADED",
  SUCCESS_POPUP_RESET: "SUCCESS_POPUP_RESET",
  ERROR_POPUP_RESET: "ERROR_POPUP_RESET",


}