export const ContactUsActionType = {
    CONTACT_US: "CONTACT_US",
    CONTACT_US_CREATE: "CONTACT_US_CREATE",
    CONTACT_US_RESET: "CONTACT_US_RESET",

    GET_CONTACTS_LIST_LOADING: "GET_CONTACTS_LIST_LOADING",
    GET_CONTACTS_LIST_LOADED: "GET_CONTACTS_LIST_LOADED",
    GET_CONTACTS_LIST_ERROR: "GET_CONTACTS_LIST_ERROR",
    GET_CONTACTS_LIST_RESET: "GET_CONTACTS_LIST_RESET",

    GET_CONTACT_FORM_LOADING: "GET_CONTACT_FORM_LOADING",
    GET_CONTACT_FORM_LOADED: "GET_CONTACT_FORM_LOADED",
    GET_CONTACT_FORM_ERROR: "GET_CONTACT_FORM_ERROR",
    GET_CONTACT_FORM_RESET: "GET_CONTACT_FORM_RESET",

    UPDATE_CONTACT_FORM_LOADING: "UPDATE_CONTACT_FORM_LOADING",
    UPDATE_CONTACT_FORM_LOADED: "UPDATE_CONTACT_FORM_LOADED",
    UPDATE_CONTACT_FORM_ERROR: "UPDATE_CONTACT_FORM_ERROR",
    UPDATE_CONTACT_FORM_RESET: "UPDATE_CONTACT_FORM_RESET",

    DOWNLOAD_EXCEL_SHEET: "DOWNLOAD_EXCEL_SHEET",

    DOWNLOAD_EXCEL_SHEET_RESET: "DOWNLOAD_EXCEL_SHEET_RESET"
}