export const CurrencyActionTypes = {
  GET_ADMIN_CURRENCY_LIST_LOADING: "GET_ADMIN_CURRENCY_LIST_LOADING",
  GET_ADMIN_CURRENCY_LIST_SUCCESS: "GET_ADMIN_CURRENCY_LIST_SUCCESS",
  GET_ADMIN_CURRENCY_LIST_FAIL: "GET_ADMIN_CURRENCY_LIST_FAIL",
  GET_ADMIN_CURRENCY_LIST_RESET: "GET_ADMIN_CURRENCY_LIST_RESET",

  SELECTED_CURRENCY_LOADING: "SELECTED_CURRENCY_LOADING",
  SELECTED_CURRENCY_SUCCESS: "SELECTED_CURRENCY_SUCCESS",
  SELECTED_CURRENCY_FAIL: "SELECTED_CURRENCY_FAIL",
  SELECTED_CURRENCY_RESET: "SELECTED_CURRENCY_RESET",

  DEFAULT_CURRENCY_LOADING: "DEFAULT_CURRENCY_LOADING",
  DEFAULT_CURRENCY_SUCCESS: "DEFAULT_CURRENCY_SUCCESS",
  DEFAULT_CURRENCY_FAIL: "DEFAULT_CURRENCY_FAIL",
  DEFAULT_CURRENCY_RESET: "DEFAULT_CURRENCY_RESET",
}