export const ProductActionTypes = {

  GET_PRODUCT_LIST_LOADING: "GET_PRODUCT_LIST_LOADING",
  GET_PRODUCT_LIST_SUCCESS: "GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_RESET: "GET_PRODUCT_LIST_RESET",
  GET_PRODUCT_LIST_FAIL: "GET_PRODUCT_LIST_FAIL",

  CUSTOMER_PRODUCT_DETAIL_LOADING: "CUSTOMER_PRODUCT_DETAIL_LOADING",
  CUSTOMER_PRODUCT_DETAIL_SUCCESS: "CUSTOMER_PRODUCT_DETAIL_SUCCESS",
  CUSTOMER_PRODUCT_DETAIL_REST: "CUSTOMER_PRODUCT_DETAIL_REST",
  CUSTOMER_PRODUCT_DETAIL_FAIL: "CUSTOMER_PRODUCT_DETAIL_FAIL",



  GET_SEARCHED_PRODUCT_LOADER_SHOW: "GET_SEARCHED_PRODUCT_LOADER_SHOW",
  GET_SEARCHED_PRODUCT_LIST_SUCCESS: "GET_SEARCHED_PRODUCT_LIST_SUCCESS",
  GET_SEARCHED_PRODUCT_LIST_FAIL: "GET_SEARCHED_PRODUCT_LIST_FAIL",


  REMOVE_CATEGORY_PRODUCT_FILTER_CHANGES: "REMOVE_CATEGORY_PRODUCT_FILTER_CHANGES",
  CHANGE_CATEGORY_PRODUCT_FILTER_CHANGES: "CHANGE_CATEGORY_PRODUCT_FILTER_CHANGES",
  CHANGE_COLLECTION_PRODUCT_FILTER_CHANGES: "CHANGE_COLLECTION_PRODUCT_FILTER_CHANGES",
  CHANGE_PRICE_PRODUCT_FILTER_CHANGES: "CHANGE_PRICE_PRODUCT_FILTER_CHANGES",
  CLEAR_ALL_PRODUCT_PAGE_FILTERS: "CLEAR_ALL_PRODUCT_PAGE_FILTERS",
  SORT_BY_PRODUCT_PAGE_FILTERS: "SORT_BY_PRODUCT_PAGE_FILTERS",
  STORED_PRODUCT_LIST_SUCCESS: "STORED_PRODUCT_LIST_SUCCESS",
  UPDATE_FILTER_PRODUCT_LIST: "UPDATE_FILTER_PRODUCT_LIST",
  UPDATE_SORT_BY_PRODUCT_LIST: "UPDATE_SORT_BY_PRODUCT_LIST",
  PAGINATION_PRODUCT_PAGE_FILTERS: "PAGINATION_PRODUCT_PAGE_FILTERS"
};