export const BlogActionTypes = {
  SELECT_ROUTE_PREVIEW: "SELECT_ROUTE_PREVIEW",
  SET_PARAMS_ID: "SET_PARAMS_ID",
  // ECOMMERCE_TEMPLATE_DOMAIN_CHECK: "ECOMMERCE_TEMPLATE_DOMAIN_CHECK",

  GET_BLOG_ITEM_LIST_LOADING: "GET_BLOG_ITEM_LIST_LOADING",
  GET_BLOG_ITEM_LIST_SUCCESS: "GET_BLOG_ITEM_LIST_SUCCESS",
  GET_BLOG_ITEM_LIST_ERROR: "GET_BLOG_ITEM_LIST_ERROR",
  GET_BLOG_ITEM_LIST_RESET: "GET_BLOG_ITEM_LIST_RESET",
}

