
export const guestAction = {
  POST_GUEST_CART_LOADING: "POST_GUEST_CART_LOADING",
  POST_GUEST_CART_SUCCESS: "POST_GUEST_CART_SUCCESS",
  POST_GUEST_CART_ERROR: "POST_GUEST_CART_ERROR",

  UPDATE_SHIPPING_PRICE: 'UPDATE_SHIPPING_PRICE',
  GUEST_CART_UPDATE_AFTER_LOGIN_LOADING: "GUEST_CART_UPDATE_AFTER_LOGIN_LOADING",
  GUEST_CART_UPDATE_AFTER_LOGIN_SUCCESS: "GUEST_CART_UPDATE_AFTER_LOGIN_SUCCESS",
  GUEST_CART_UPDATE_AFTER_LOGIN_ERROR: "GUEST_CART_UPDATE_AFTER_LOGIN_ERROR",
  GUEST_CART_UPDATE_AFTER_LOGIN_RESET: "GUEST_CART_UPDATE_AFTER_LOGIN_RESET",

  GET_GUEST_ORDER_LIST_LOADING: "GET_GUEST_ORDER_LIST_LOADING",
  GET_GUEST_ORDER_LIST_SUCCESS: "GET_GUEST_ORDER_LIST_SUCCESS",
  GET_GUEST_ORDER_LIST_ERROR: "GET_GUEST_ORDER_LIST_ERROR",

  UPDATE_ORDER_STATUS_LOADING: "UPDATE_ORDER_STATUS_LOADING",
  GET_SINGLE_ORDER_SUCCESS: "GET_SINGLE_ORDER_SUCCESS",
  UPDATE_ORDER_STATUS_REJECT: "UPDATE_ORDER_STATUS_REJECT",

  GET_GUEST_CART_LOADING:"GET_GUEST_CART_LOADING",
  GET_GUEST_CART_SUCCESS:"GET_GUEST_CART_SUCCESS",
  GET_GUEST_CART_ERROR:"GET_GUEST_CART_ERROR",


}
