export const CollectionActionTypes = {
    GET_COLLECTION_LIST_LOADING: "GET_COLLECTION_LIST_LOADING",
    GET_COLLECTION_LIST_SUCCESS: "GET_COLLECTION_LIST_SUCCESS",
    GET_COLLECTION_LIST_FAIL: "GET_COLLECTION_LIST_FAIL",
    GET_COLLECTION_LIST_RESET: "GET_COLLECTION_LIST_RESET",
}